# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '选课表',
                'verbose_name_plural': '选课表',
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生表', 'verbose_name_plural': '学生表'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老师表', 'verbose_name_plural': '老师表'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enroll', to='course.Course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_enroll', to='course.Student'),
        ),
    ]
